//! VibeLang DSP - SynthDef generation and UGen DSL.
//!
//! This crate provides the synthesis definition layer for VibeLang:
//!
//! - **Graph** - Graph IR for synth construction (nodes, inputs, parameters)
//! - **Encoder** - Binary encoding to SuperCollider's scsyndef format
//! - **NodeRef** - Opaque node references with arithmetic operators
//! - **Helpers** - High-level DSP functions (envelopes, mixing, etc.)
//! - **UGens** - Auto-generated UGen function library
//! - **Builder** - SynthDef builder for closure-based definition
//! - **API** - Rhai API for define_synthdef and define_fx
//!
//! # Architecture
//!
//! SynthDefs are built using a thread-local graph builder pattern:
//!
//! 1. Set the active builder with [`set_active_builder`]
//! 2. Add parameters, constants, and UGen nodes
//! 3. Finalize with [`clear_active_builder`] and get the [`GraphIR`]
//! 4. Encode to binary with [`encode_synthdef`]

pub mod api;
pub mod builder;
pub mod encoder;
pub mod errors;
pub mod graph;
pub mod helpers;
pub mod rhainodes;

// The UGen module is auto-generated by build.rs
#[allow(clippy::too_many_arguments)]
mod ugens {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

pub use api::{
    register_synthdef_api, set_deploy_callback, synthdef_exists, effect_exists,
    synthdef_or_effect_exists, get_synthdef_param_defaults, get_effect_param_defaults,
    register_synthdef_ir, SynthDefBuilderHandle, FxBuilderHandle,
};
pub use builder::SynthDef;
pub use encoder::encode_synthdef;
pub use errors::{Result, SynthDefError};
pub use graph::{
    clear_active_builder, set_active_builder, with_builder, GraphBuilderInner, GraphIR, Input,
    ParamSpec, Rate, UGenNode,
};
pub use helpers::{
    amp_to_db, channel, channels, db_to_amp, detune_spread, dup, env_gen, env_gen_with_env,
    env_gen_with_env_n, in_ar, in_ar_n, mix, replace_out_ar, replace_out_ar_n, Env, EnvGenBuilder,
};
pub use rhainodes::{register_node_ref, NodeRef};

/// Re-export the generated UGen registration function.
pub use ugens::register_generated_ugens;

/// Register all DSP types and functions with a Rhai engine.
/// This includes UGens, NodeRef, helpers, and SynthDef builder API.
pub fn register_dsp_api(engine: &mut rhai::Engine) {
    register_node_ref(engine);
    helpers::register_helpers(engine);
    register_generated_ugens(engine);
    register_synthdef_api(engine);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rate_ordering() {
        assert!(Rate::Scalar < Rate::Control);
        assert!(Rate::Control < Rate::Audio);
    }

    #[test]
    fn test_input_constant() {
        let input = Input::Constant(440.0);
        if let Input::Constant(val) = input {
            assert!((val - 440.0).abs() < 0.001);
        } else {
            panic!("Expected constant input");
        }
    }

    #[test]
    fn test_node_ref_encoding() {
        let node_ref = NodeRef::new_with_output(5, 2);
        assert_eq!(node_ref.id(), 5);
        assert_eq!(node_ref.output_index(), 2);
    }
}
