//! VibeLang DSP - SynthDef generation and UGen DSL.
//!
//! This crate provides the synthesis definition layer for VibeLang:
//!
//! - **Graph** - Graph IR for synth construction (nodes, inputs, parameters)
//! - **Encoder** - Binary encoding to SuperCollider's scsyndef format
//! - **NodeRef** - Opaque node references with arithmetic operators
//! - **Helpers** - High-level DSP functions (envelopes, mixing, etc.)
//! - **UGens** - Auto-generated UGen function library
//! - **Builder** - SynthDef builder for closure-based definition
//! - **API** - Rhai API for define_synthdef and define_fx
//!
//! # Architecture
//!
//! SynthDefs are built using a thread-local graph builder pattern:
//!
//! 1. Set the active builder with [`set_active_builder`]
//! 2. Add parameters, constants, and UGen nodes
//! 3. Finalize with [`clear_active_builder`] and get the [`GraphIR`]
//! 4. Encode to binary with [`encode_synthdef`]

pub mod api;
pub mod builder;
pub mod encoder;
pub mod errors;
pub mod graph;
pub mod helpers;
pub mod notes;
pub mod rhainodes;
pub mod system_synthdefs;

// The UGen module is auto-generated by build.rs
#[allow(clippy::too_many_arguments)]
mod ugens {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

pub use api::{
    clear_effect_registry, clear_synthdef_hash_registry, clear_synthdef_inputs_registry,
    clear_synthdef_outputs_registry, clear_synthdef_registry, effect_exists, get_all_effect_names,
    get_all_effects_encoded, get_all_synthdefs_encoded, get_effect_param_defaults,
    get_synthdef_hash, get_synthdef_inputs, get_synthdef_outputs, get_synthdef_param_defaults,
    get_synthdef_param_defaults_arc, register_effect_ir, register_synthdef_api,
    register_synthdef_hash, register_synthdef_inputs, register_synthdef_ir,
    register_synthdef_outputs, set_deploy_callback, synthdef_exists, synthdef_or_effect_exists,
    DspDefinitionIr, DspDefinitionKind, FxBuilderHandle, StagedDspRegistry, SynthDefBuilderHandle,
};
pub use builder::{InputPort, OutputPort, PortRate, SynthDef};
pub use encoder::encode_synthdef;
pub use errors::{Result, SynthDefError};
pub use graph::{
    clear_active_builder, set_active_builder, with_builder, GraphBuilderInner, GraphIR, Input,
    ParamSpec, Rate, UGenNode,
};
pub use helpers::{
    amp_to_db, channel, channels, db_to_amp, detune_spread, dup, env_gen, env_gen_with_env,
    env_gen_with_env_n, in_ar, in_ar_n, mix, replace_out_ar, replace_out_ar_n, Env, EnvGenBuilder,
};
pub use notes::{
    parse_note_name, parse_note_name_raw, parse_note_name_raw_strict, parse_note_name_strict,
    NoteParseError,
};
pub use rhainodes::{register_node_ref, NodeRef};

/// Re-export the generated UGen registration function.
pub use ugens::{register_generated_ugens, register_generated_ugens_v2};

/// Register all DSP types and functions with a Rhai engine.
/// This includes UGens, NodeRef, helpers, and SynthDef builder API.
pub fn register_dsp_api(engine: &mut rhai::Engine) {
    register_node_ref(engine);
    helpers::register_helpers_for_profile(engine, helpers::UgenAdapterProfile::V1Compatibility);
    register_generated_ugens(engine);
    register_synthdef_api(engine);
}

/// Register DSP types and functions with strict vibe-api 2 UGen adapters.
pub fn register_dsp_api_v2(engine: &mut rhai::Engine) {
    register_node_ref(engine);
    helpers::register_helpers_for_profile(engine, helpers::UgenAdapterProfile::V2Strict);
    register_generated_ugens_v2(engine);
    register_synthdef_api(engine);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rate_ordering() {
        assert!(Rate::Scalar < Rate::Control);
        assert!(Rate::Control < Rate::Audio);
    }

    #[test]
    fn test_input_constant() {
        let input = Input::Constant(440.0);
        if let Input::Constant(val) = input {
            assert!((val - 440.0).abs() < 0.001);
        } else {
            panic!("Expected constant input");
        }
    }

    #[test]
    fn test_node_ref_encoding() {
        let node_ref = NodeRef::new_with_output(5, 2);
        assert_eq!(node_ref.id(), 5);
        assert_eq!(node_ref.output_index(), 2);
    }

    #[test]
    fn generated_runtime_adapter_source_has_no_unwind_or_silent_default_path() {
        let source = include_str!(concat!(env!("OUT_DIR"), "/generated.rs"));
        let helpers_source = include_str!("helpers.rs");
        for forbidden in [
            ".unwrap()",
            ".expect(",
            "panic!(",
            ".unwrap_or(0.0)",
            ".cast()",
        ] {
            assert!(
                !source.contains(forbidden),
                "generated adapter source contains forbidden path {forbidden}"
            );
        }
        let accepted_overloads = 5_962;
        let profile_split_overloads = source
            .matches("helpers::UgenAdapterProfile::V1Compatibility => {")
            .count();
        assert_eq!(profile_split_overloads, 12);
        assert_eq!(
            source
                .matches("helpers::UgenAdapterProfile::V2Strict => {")
                .count(),
            profile_split_overloads
        );
        let generated_adapter_sites = source.matches("helpers::adapt_ugen_call(").count();
        assert_eq!(
            generated_adapter_sites,
            accepted_overloads + profile_split_overloads,
            "profile-split overloads must have exactly one adapter site per registration body"
        );
        assert_eq!(
            generated_adapter_sites - profile_split_overloads,
            accepted_overloads,
            "each installed profile must retain one adapter per accepted overload"
        );

        let v1_typed_dc_helpers = helpers_source
            .split_once("if profile == UgenAdapterProfile::V1Compatibility {")
            .expect("v1 typed DC compatibility registrations")
            .1;
        assert_eq!(
            v1_typed_dc_helpers.matches("adapt_ugen_call(").count(),
            2,
            "typed v1 DC compatibility callers are outside the generated overload inventory"
        );
        assert!(v1_typed_dc_helpers.contains("engine.register_fn(\"dc_ar\""));
        assert!(v1_typed_dc_helpers.contains("engine.register_fn(\"dc_kr\""));
    }
}
