/* Generated by scripts/public-artifacts.sh from crates/vibelang-wasm/src/lib.rs. */
/* Raw wasm-bindgen JS/wasm and private InitOutput ABI fields are intentionally excluded. */

export interface VibelangResult {
  success: boolean;
  error: string | null;
  groups: number;
  voices: number;
  patterns: number;
  melodies: number;
  tempo: number;
}

export interface VibelangCompiledSynthdef {
  name: string;
  data: Uint8Array | number[];
}

export interface VibelangError {
  message: string;
  name?: string;
  stack?: string;
}

export interface VibelangBridge {
  loadSynthdef(name: string, data: Uint8Array): Promise<unknown>;
}

declare global {
  interface Window {
    vibelangBridge?: VibelangBridge;
  }
}

export class VibelangEngine {
  free(): void;
  [Symbol.dispose](): void;
  constructor();
  execute(script: string): VibelangResult;
  getSynthdefs(): VibelangCompiledSynthdef[];
  static getSystemSynthdefs(): VibelangCompiledSynthdef[];
  clearSynthdefs(): void;
  static parseNote(note: string): number;
  static dbToAmp(db: number): number;
  static ampToDb(amp: number): number;
}

export class VibelangRuntime {
  free(): void;
  [Symbol.dispose](): void;
  constructor();
  init(): Promise<void>;
  execute(script: string): Promise<VibelangResult>;
  tick(): Promise<void>;
  start(): Promise<void>;
  stop(): Promise<void>;
  stopAll(): Promise<void>;
  static getSystemSynthdefs(): VibelangCompiledSynthdef[];
  isInitialized(): boolean;
  static parseNote(note: string): number;
  static dbToAmp(db: number): number;
  static ampToDb(amp: number): number;
}

export function initPanicHook(): void;
export function log(message: string): void;
export function version(): string;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly [exportName: string]: unknown;
}
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;
export default function __wbg_init(module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
