/* Generated by scripts/public-artifacts.sh from crates/vibelang-wasm/src/lib.rs. */
/* wasm-bindgen start hooks, raw JS/wasm, and private InitOutput ABI fields are intentionally excluded. */

export type VibelangExecutionFailurePhase = "evaluate" | "initialize" | "bridge" | "dispatch" | "runtime";

export interface VibelangMutationReceipt {
  schema_version: number;
  attempt_id: string;
  runtime_epoch: string;
  revision: string | null;
  event_sequence: string;
  request: unknown;
  state: unknown;
  previous_confirmed_revision: string | null;
  timestamps: unknown;
  diagnostics: unknown[];
}

export interface VibelangResult {
  /** @deprecated Evaluation-only compatibility signal. Inspect receipt for runtime truth. */
  success: boolean;
  legacy_success_scope: string;
  error: string | null;
  failure: VibelangExecutionFailure | null;
  receipt: VibelangMutationReceipt | null;
  groups: number;
  voices: number;
  patterns: number;
  melodies: number;
  tempo: number;
}

export interface VibelangExecutionFailure {
  phase: VibelangExecutionFailurePhase;
  code: string;
  message: string;
}

export interface VibelangCompiledSynthdef {
  name: string;
  data: Uint8Array | number[];
}

export interface VibelangError {
  message: string;
  name?: string;
  stack?: string;
}

export interface VibelangBridge {
  loadSynthdef(name: string, data: Uint8Array): Promise<unknown>;
}

declare global {
  var vibelangBridge: VibelangBridge | undefined;
  interface Window {
    vibelangBridge?: VibelangBridge;
  }
}

export class VibelangEngine {
  free(): void;
  [Symbol.dispose](): void;
  constructor();
  execute(script: string): VibelangResult;
  getSynthdefs(): VibelangCompiledSynthdef[];
  static getSystemSynthdefs(): VibelangCompiledSynthdef[];
  clearSynthdefs(): void;
  static parseNote(note: string): number;
  static dbToAmp(db: number): number;
  static ampToDb(amp: number): number;
}

export class VibelangRuntime {
  free(): void;
  [Symbol.dispose](): void;
  constructor();
  init(): Promise<void>;
  execute(script: string): Promise<VibelangResult>;
  tick(): Promise<void>;
  getReceipt(attempt_id: string): VibelangMutationReceipt;
  continueBestEffort(attempt_id: string): void;
  start(): Promise<void>;
  stop(): Promise<void>;
  stopAll(): Promise<void>;
  static getSystemSynthdefs(): VibelangCompiledSynthdef[];
  isInitialized(): boolean;
  static parseNote(note: string): number;
  static dbToAmp(db: number): number;
  static ampToDb(amp: number): number;
}

export function log(message: string): void;
export function version(): string;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;
export type SyncInitInput = BufferSource | WebAssembly.Module;
export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly [exportName: string]: unknown;
}
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;
export default function __wbg_init(module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
